// ── CONFIG ──
const firebaseConfig = {
  apiKey: "AIzaSyCRLENh_UEBdXzukzpXVHHTltSapqyNWVc",
  authDomain: "brightwebaccbase.firebaseapp.com",
  projectId: "brightwebaccbase",
  storageBucket: "brightwebaccbase.firebasestorage.app",
  messagingSenderId: "482143691238",
  appId: "1:482143691238:web:67dd3871bc93bf08c03627",
  measurementId: "G-LXMQJM43PN"
};
const ADMIN_EMAIL = "mcdg5444@gmail.com";

// ── PARTICLES CONFIG ──
const PARTICLES_CONFIG = {
  "particles": {
    "number": { "value": 50, "density": { "enable": true, "value_area": 300 } },
    "color": { "value": "#37b1f8" },
    "shape": { "type": "circle", "stroke": { "width": 4, "color": "#1d4470" } },
    "opacity": { "value": 1, "random": true, "anim": { "enable": true, "speed": 1, "opacity_min": 0.7, "sync": false } },
    "size": { "value": 5, "random": true, "anim": { "enable": true, "speed": 5, "size_min": 4, "sync": true } },
    "line_linked": { "enable": true, "distance": 130, "color": "#ffffff", "opacity": 0.3, "width": 1 },
    "move": { "enable": true, "speed": 4, "direction": "none", "random": true, "straight": false, "out_mode": "out", "bounce": false }
  },
  "interactivity": {
    "detect_on": "canvas",
    "events": { "onhover": { "enable": true, "mode": "bubble" }, "onclick": { "enable": true, "mode": "push" }, "resize": true },
    "modes": {
      "bubble": { "distance": 100, "size": 10, "duration": 0.97, "opacity": 0.99, "speed": 3 },
      "push": { "particles_nb": 4 }, "remove": { "particles_nb": 2 }
    }
  },
  "retina_detect": true
};

// ── INIT ──
firebase.initializeApp(firebaseConfig);
const auth = firebase.auth();
const db = firebase.firestore();

const $ = id => document.getElementById(id);
let appData = null;
let ghPagesMap = new Map(); // id -> title
let allResults = []; // Store results for filtering

// Particles Init
particlesJS('particles-js', PARTICLES_CONFIG);

function showLoad() { $('loading').classList.add('show'); }
function hideLoad() { $('loading').classList.remove('show'); }

function signOut() { 
  auth.signOut().then(() => window.location.href = 'index.html'); 
}

// ── AUTH CHECK ──
auth.onAuthStateChanged(async user => {
  if (user) {
    if (user.email !== ADMIN_EMAIL) {
      // Not admin
      $('unauthorized-msg').style.display = 'block';
      $('page-admin').style.display = 'none';
      $('header').style.display = 'none';
    } else {
      // Is admin
      $('user-info').textContent = user.displayName || user.email;
      $('header').style.display = 'flex';
      $('unauthorized-msg').style.display = 'none';
      $('page-admin').style.display = 'block';
      
      showLoad();
      await loadGhPagesData();
      hideLoad();
    }
  } else {
    // Not logged in
    window.location.href = 'index.html';
  }
});

// ── LOAD GH PAGES DATA ──
async function loadGhPagesData() {
  try {
    const doc = await db.collection('app_data').doc('courses').get();
    if (doc.exists) {
      appData = JSON.parse(doc.data().json);
      ghPagesMap.clear();
      
      // Traverse the tree to get all lessons with a valid youtubeId
      appData.courses.forEach(course => {
        traverseTree(course.tree);
      });
      console.log(`Loaded ${ghPagesMap.size} videos from GitHub Pages data.`);
    } else {
      alert("Không tìm thấy dữ liệu khóa học trên Firestore.");
    }
  } catch(e) {
    console.error(e);
    alert("Lỗi tải dữ liệu: " + e.message);
  }
}

function traverseTree(nodes) {
  nodes.forEach(node => {
    if (node.type === 'lesson') {
      if (node.youtubeId) {
        // Here we map the ID string (e.g. 010101) to its title
        // In this implementation, the lesson ID generated by the python script
        // is stored as node.id, but it's usually formatted like "01-01-01".
        // The script id_str is like "010101".
        // To be safe, we normalize both or just use the extracted ID from the title if needed.
        
        // Wait, node.id is e.g. "01-01-01". We can normalize it to "010101".
        const normalizedId = node.id.replace(/-/g, '');
        ghPagesMap.set(normalizedId, node.title);
      }
    } else if (node.children) {
      traverseTree(node.children);
    }
  });
}

// ── UTILS ──
function normalizeId(text) {
  const match = text.trim().match(/^([a-zA-Z0-9_-]+)/);
  if (match) {
    return match[1].replace(/-/g, ''); // replace hyphens to match 010101 format
  }
  return text.trim();
}

function extractIds(inputStr) {
  if (!inputStr.trim()) return new Set();
  
  let ids = [];
  try {
    let parsed = JSON.parse(inputStr);
    if (Array.isArray(parsed)) {
      parsed.forEach(item => {
        let id = normalizeId(String(item));
        if (id) ids.push(id);
      });
      return new Set(ids);
    }
  } catch (e) { /* ignore JSON parse error */ }

  let lines = inputStr.split('\n');
  for (let line of lines) {
    let clean = line.trim();
    if (!clean) continue;
    let id = normalizeId(clean);
    if (id) ids.push(id);
  }
  return new Set(ids);
}

// ── CHECKING LOGIC ──
function runCheck() {
  const dlInput = $('input-downloaded').value;
  const ytInput = $('input-uploaded').value;
  
  const dlSet = extractIds(dlInput);
  const ytSet = extractIds(ytInput);
  
  // GH Pages set is keys of ghPagesMap
  const ghSet = new Set(ghPagesMap.keys());
  
  $('count-dl').textContent = dlSet.size;
  $('count-yt').textContent = ytSet.size;
  $('count-gh').textContent = ghSet.size;
  
  // Build report
  allResults = [];
  
  // Combine all known IDs
  let allKnownIds = new Set([...dlSet, ...ytSet, ...ghSet]);
  
  for (let id of allKnownIds) {
    let inDl = dlSet.has(id);
    let inYt = ytSet.has(id);
    let inGh = ghSet.has(id);
    
    let title = ghPagesMap.get(id) || "—";
    let statusClass = "info";
    let statusText = "OK";
    let details = "";
    let filterCat = "all";
    
    if (inDl && inYt && inGh) {
      statusClass = "success";
      statusText = "HOÀN THẢO";
      details = "Có mặt đầy đủ trên cả 3 nguồn";
      filterCat = "ok";
    } else {
      let missingFrom = [];
      if (!inDl) missingFrom.push("Download");
      if (!inYt) missingFrom.push("YouTube");
      if (!inGh) missingFrom.push("GH Pages");
      
      if (!inGh && inYt) {
        statusClass = "error";
        statusText = "THIẾU TRÊN WEB";
        details = "Đã upload YouTube nhưng chưa gắn link lên web.";
        filterCat = "missing-gh";
      } else if (!inYt && inDl) {
        statusClass = "warning";
        statusText = "CHƯA UPLOAD";
        details = "Đã download nhưng chưa up lên YouTube.";
        filterCat = "missing-yt";
      } else if (inGh && !inDl && !inYt) {
        statusClass = "warning";
        statusText = "ID BẤT THƯỜNG";
        details = "Web có hiển thị nhưng không thấy trong danh sách nguồn.";
        filterCat = "ghost-gh";
      } else {
        statusClass = "error";
        statusText = "LỖI PARITY";
        details = `Thiếu ở: ${missingFrom.join(', ')}`;
        filterCat = "other";
      }
    }
    
    allResults.push({ id, title, statusClass, statusText, details, filterCat });
  }
  
  // Sort: errors first, then warnings, then successes
  allResults.sort((a, b) => {
    const order = { "error": 1, "warning": 2, "info": 3, "success": 4 };
    return order[a.statusClass] - order[b.statusClass];
  });
  
  $('report-section').style.display = 'block';
  renderTable("all");
}

// ── RENDERING ──
function renderTable(filter) {
  const tbody = $('result-body');
  tbody.innerHTML = '';
  
  let toShow = allResults;
  if (filter !== "all") {
    toShow = allResults.filter(r => r.filterCat === filter);
  }
  
  if (toShow.length === 0) {
    tbody.innerHTML = `<tr><td colspan="4" style="text-align: center; color: var(--text-muted);">Không có dữ liệu phù hợp</td></tr>`;
    return;
  }
  
  toShow.forEach(r => {
    const tr = document.createElement('tr');
    tr.innerHTML = `
      <td><strong>${r.id}</strong></td>
      <td>${r.title}</td>
      <td><span class="status ${r.statusClass}">${r.statusText}</span></td>
      <td>${r.details}</td>
    `;
    tbody.appendChild(tr);
  });
}

// Events for filters
document.querySelectorAll('.filter-btn').forEach(btn => {
  btn.addEventListener('click', (e) => {
    document.querySelectorAll('.filter-btn').forEach(b => b.classList.remove('active'));
    e.target.classList.add('active');
    renderTable(e.target.dataset.filter);
  });
});
